Feature validation enhancements 2023
mapswipe/mapswipe pull request #796
Opened 2023-06-15 08:48 UTC by samshara

Addresses 

- [ ] https://github.com/mapswipe/mapswipe/issues/789
- [ ] https://github.com/mapswipe/mapswipe/issues/788
- [ ] https://github.com/mapswipe/mapswipe/issues/786
- [ ] https://github.com/mapswipe/mapswipe/issues/791
- [ ] https://github.com/mapswipe/mapswipe/issues/792
- [ ] https://github.com/mapswipe/mapswipe/issues/790
### Additional cross application linked issues
- [ ] https://github.com/mapswipe/python-mapswipe-workers/issues/822
- [ ] https://github.com/mapswipe/python-mapswipe-workers/issues/842
- [ ] https://github.com/mapswipe/python-mapswipe-workers/issues/830

2023-06-28 04:07 UTC, frozenhelium approved these changes

2023-07-04 05:34 UTC, tnagorra commented on src/shared/common/InformationPage.js
> +                                )}
There is no difference between second and third expression

2023-07-04 05:47 UTC, tnagorra requested changes

2023-07-04 05:47 UTC, tnagorra commented on src/shared/common/Tutorial/index.js
> +        console.warn('icon', icon);
Let's remove the warning

2023-07-04 05:47 UTC, tnagorra commented on src/shared/views/BuildingFootprint/TutorialIntro.js
> +    const fallbackInformationPage: ProjectInformation = [
Let's move this outside the function

2023-07-04 05:47 UTC, tnagorra commented on src/shared/views/BuildingFootprint/index.js
> +                <Text style={styles.header}>TThis is good</Text>
TThis is not good.

2023-07-05 03:10 UTC, frozenhelium commented
@laurentS This is ready to be be deployed! Let's go ahead with the release! CC: @danbjoseph

2023-07-06 15:26 UTC, tnagorra approved these changes

2023-07-10 08:08 UTC, merged